import './globals.css';

import type { Metadata } from 'next';

import GlobalHeaderLarge from '@/components/GlobalHeader/GlobaHeaderLarge';
import GlobalHeaderSmall from '@/components/GlobalHeader/GlobalHeaderSmall';

import { primary } from './font';
import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${primary.className} antialiased`}>
        <Providers>
          <GlobalHeaderLarge className='hidden md:flex' />
          <GlobalHeaderSmall className='flex md:hidden' />
          {children}
        </Providers>
      </body>
    </html>
  );
}
