import './globals.css';

import type { Metadata } from 'next';

import GlobalHeader from '@/components/GlobalHeader/GlobalHeader';
import Sidebar from '@/components/GlobalHeader/Sidebar';

import { primary } from './font';
import { Providers } from './Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${primary.className} antialiased`}>
        <Providers>
          <GlobalHeader className='flex md:hidden' />
          <div className='flex flex-row'>
            <Sidebar className='hidden md:flex' />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
