/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsFrequencyType =
  (typeof _36EnumsFrequencyType)[keyof typeof _36EnumsFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsFrequencyType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  ONCE: 'ONCE',
} as const;
