/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsRole = (typeof _36EnumsRole)[keyof typeof _36EnumsRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
} as const;
