/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type _36EnumsOauthProvider =
  (typeof _36EnumsOauthProvider)[keyof typeof _36EnumsOauthProvider];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _36EnumsOauthProvider = {
  GOOGLE: 'GOOGLE',
  KAKAO: 'KAKAO',
} as const;
