/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * 간편 로그인을 위한 인증 키 입니다.

* Google 의 경우에는 "클라이언트 id" 입니다.
* Kakao 의 경우에는 "REST API 키" 입니다.


실습을 위해 발급받은 키를 등록해주세요. 실제 서비스에서 사용 하는 키는 등록하시면 안됩니다.
 */
export type AppKey = string;
