/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * 간편 로그인을 위한 비밀 키 입니다.

* Google 의 경우에는 필요하지 않습니다.
* Kakao 의 경우에는 필요하지 않습니다.
 */
export type AppSecret = string;
