/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleWriter } from './articleWriter';
import type { ArticleListTypeImage } from './articleListTypeImage';
import type { ArticleTitle } from './articleTitle';
import type { Id } from './id';

export interface ArticleListType {
  updatedAt: string;
  createdAt: string;
  likeCount: number;
  writer: ArticleWriter;
  /** @nullable */
  image: ArticleListTypeImage;
  title: ArticleTitle;
  id: Id;
}
