/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { CommentTypeWriter } from './commentTypeWriter';
import type { Id } from './id';

export interface CommentType {
  writer: CommentTypeWriter;
  updatedAt: string;
  createdAt: string;
  content: string;
  id: Id;
}
