/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UrlType } from './urlType';
import type { Nickname } from './nickname';

export interface CreateGroupBody {
  image?: UrlType;
  name: Nickname;
}
