/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRecurringTasks200Recurring } from './createRecurringTasks200Recurring';

export type CreateRecurringTasks200 = {
  recurring: CreateRecurringTasks200Recurring;
};
