/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UrlType } from './urlType';
import type { ArticleContent } from './articleContent';
import type { ArticleTitle } from './articleTitle';

export interface CreateArticleBody {
  image?: UrlType;
  content: ArticleContent;
  title: ArticleTitle;
}
