/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type Create200 = {
  name: string;
  image: string;
  updatedAt: string;
  createdAt: string;
  id: number;
};
