/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type DailyRecurringCreateBodyFrequencyType =
  (typeof DailyRecurringCreateBodyFrequencyType)[keyof typeof DailyRecurringCreateBodyFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DailyRecurringCreateBodyFrequencyType = {
  DAILY: 'DAILY',
} as const;
