/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type DeleteTaskComment403 = (typeof DeleteTaskComment403)[keyof typeof DeleteTaskComment403];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteTaskComment403 = {
  NUMBER_403: 403,
} as const;
