/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type DeleteTaskComment404 = (typeof DeleteTaskComment404)[keyof typeof DeleteTaskComment404];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteTaskComment404 = {
  NUMBER_404: 404,
} as const;
