/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type FrequencyType = (typeof FrequencyType)[keyof typeof FrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FrequencyType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  ONCE: 'ONCE',
} as const;
