/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { Get200MembersItem } from './get200MembersItem';
import type { Get200TaskListsItem } from './get200TaskListsItem';

export type Get200 = {
  teamId: string;
  updatedAt: string;
  createdAt: string;
  image: string;
  name: string;
  id: number;
  members: Get200MembersItem[];
  taskLists: Get200TaskListsItem[];
};
