/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type GetByTaskId200ItemAllOfUser = {
  image: string;
  nickname: string;
  id: number;
};
