/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type GetByTaskId404 = (typeof GetByTaskId404)[keyof typeof GetByTaskId404];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetByTaskId404 = {
  NUMBER_404: 404,
} as const;
