/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetByTaskId200ItemAllOf } from './getByTaskId200ItemAllOf';
import type { GetByTaskId200ItemAllOfThree } from './getByTaskId200ItemAllOfThree';

export type GetByTaskId200Item = GetByTaskId200ItemAllOf & GetByTaskId200ItemAllOfThree;
