/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetByTaskId200ItemAllOfUser } from './getByTaskId200ItemAllOfUser';

export type GetByTaskId200ItemAllOf = {
  user: GetByTaskId200ItemAllOfUser;
};
