/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetMemberships200ItemAllOf } from './getMemberships200ItemAllOf';
import type { GetMemberships200ItemAllOfThree } from './getMemberships200ItemAllOfThree';

export type GetMemberships200Item = GetMemberships200ItemAllOf & GetMemberships200ItemAllOfThree;
