/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsRole } from './_36EnumsRole';

export type GetMemberships200ItemAllOfThree = {
  role: _36EnumsRole;
  userImage: string;
  userEmail: string;
  userName: string;
  groupId: number;
  userId: number;
};
