/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetMemberships200ItemAllOfGroup } from './getMemberships200ItemAllOfGroup';

export type GetMemberships200ItemAllOf = {
  group: GetMemberships200ItemAllOfGroup;
};
