/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200MembershipsItemAllOf } from './getUser200MembershipsItemAllOf';
import type { GetUser200MembershipsItemAllOfThree } from './getUser200MembershipsItemAllOfThree';

export type GetUser200MembershipsItem = GetUser200MembershipsItemAllOf &
  GetUser200MembershipsItemAllOfThree;
