/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GetUser200MembershipsItemAllOfGroup } from './getUser200MembershipsItemAllOfGroup';

export type GetUser200MembershipsItemAllOf = {
  group: GetUser200MembershipsItemAllOfGroup;
};
