/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { GroupUpdateBodyImage } from './groupUpdateBodyImage';
import type { Nickname } from './nickname';

export interface GroupUpdateBody {
  /** @nullable */
  image?: GroupUpdateBodyImage;
  name?: Nickname;
}
