/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { ListDoneTasks200TasksDoneItem } from './listDoneTasks200TasksDoneItem';

export type ListDoneTasks200 = {
  tasksDone: ListDoneTasks200TasksDoneItem[];
};
