/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { ListArticleOrder } from './listArticleOrder';

export type ListArticlesParams = {
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 페이지 당 게시글 수
   */
  pageSize?: number;
  /**
   * 정렬 기준
   */
  orderBy?: ListArticleOrder;
  /**
   * 검색 키워드
   */
  keyword?: string;
};
