/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

export type ListArticleOrder = (typeof ListArticleOrder)[keyof typeof ListArticleOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListArticleOrder = {
  recent: 'recent',
  like: 'like',
} as const;
