/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type MonthlyRecurringCreateBodyFrequencyType =
  (typeof MonthlyRecurringCreateBodyFrequencyType)[keyof typeof MonthlyRecurringCreateBodyFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MonthlyRecurringCreateBodyFrequencyType = {
  MONTHLY: 'MONTHLY',
} as const;
