/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { OauthAppAppSecret } from './oauthAppAppSecret';
import type { AppKey } from './appKey';
import type { _36EnumsOauthProvider } from './_36EnumsOauthProvider';
import type { Id } from './id';

export interface OauthApp {
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  appSecret: OauthAppAppSecret;
  appKey: AppKey;
  provider: _36EnumsOauthProvider;
  teamId: string;
  id: Id;
}
