/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * 간편 로그인 과정을 통해 발급받은 토큰입니다.<br />

* Google 의 경우에는 <b>Google Id 토큰</b>(JWT) 입니다.
* Kakao 의 경우에는 <b>인가 코드</b> 입니다.
 */
export type OauthToken = string;
