/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleListType } from './articleListType';

export interface OffsetBasedPaginationResponseArticleListType {
  totalCount: number;
  list: ArticleListType[];
}
