/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { PickUpdateUserBodyExcludeKeyofUpdateUserBodyEncryptedPassword } from './pickUpdateUserBodyExcludeKeyofUpdateUserBodyEncryptedPassword';

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitUpdateUserBodyEncryptedPassword =
  PickUpdateUserBodyExcludeKeyofUpdateUserBodyEncryptedPassword;
