/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type OnceRecurringCreateBodyFrequencyType =
  (typeof OnceRecurringCreateBodyFrequencyType)[keyof typeof OnceRecurringCreateBodyFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnceRecurringCreateBodyFrequencyType = {
  ONCE: 'ONCE',
} as const;
