/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * @minLength 8
 * @pattern ^([a-z]|[A-Z]|[0-9]|[!@#$%^&*])+$
 */
export type Password = string;
