/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickUpdateUserBodyExcludeKeyofUpdateUserBodyEncryptedPassword {
  nickname?: string;
  image?: string;
}
