/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type PostComment404 = (typeof PostComment404)[keyof typeof PostComment404];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostComment404 = {
  NUMBER_404: 404,
} as const;
