/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { PostComment200User } from './postComment200User';

export type PostComment200 = {
  content: string;
  updatedAt: string;
  createdAt: string;
  id: number;
  user: PostComment200User;
};
