/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UrlType } from './urlType';
import type { Password } from './password';
import type { Nickname } from './nickname';
import type { Email } from './email';

export interface SignUpRequestBody {
  image?: UrlType;
  passwordConfirmation: Password;
  password: Password;
  nickname: Nickname;
  email: Email;
}
