/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { SignUpResponseUser } from './signUpResponseUser';

export interface SignUpResponse {
  refreshToken: string;
  accessToken: string;
  user: SignUpResponseUser;
}
