/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { OauthToken } from './oauthToken';

export interface SignInWithOauthRequestBody {
  /** code를 얻을 때 사용하였던 state 값을 그대로 사용합니다. */
  state?: string;
  /** Kakao 의 경우에는 필수입니다.<br/>
인가 코드를 얻을 때 사용하였던 redirect_uri 값을 그대로 사용합니다. */
  redirectUri?: string;
  token: OauthToken;
}
