/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { Email } from './email';

export type SignUpResponseUserAllOf = {
  email: Email;
};
