/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { Password } from './password';
import type { Email } from './email';

export interface SignInRequestBody {
  password: Password;
  email: Email;
}
