/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type TaskDoneByUser = {
  /** @nullable */
  image?: string | null;
  nickname?: string;
  id: number;
} | null;
