/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { MonthlyRecurringCreateBody } from './monthlyRecurringCreateBody';
import type { WeeklyRecurringCreateBody } from './weeklyRecurringCreateBody';
import type { DailyRecurringCreateBody } from './dailyRecurringCreateBody';
import type { OnceRecurringCreateBody } from './onceRecurringCreateBody';

export type TaskRecurringCreateDto =
  | MonthlyRecurringCreateBody
  | WeeklyRecurringCreateBody
  | DailyRecurringCreateBody
  | OnceRecurringCreateBody;
