/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { TaskDoneBy } from './taskDoneBy';
import type { TaskWriter } from './taskWriter';
import type { FrequencyType } from './frequencyType';

export interface Task {
  /** @nullable */
  doneBy: TaskDoneBy;
  /** @nullable */
  writer?: TaskWriter;
  displayIndex: number;
  commentCount: number;
  /** @nullable */
  deletedAt: string | null;
  recurringId: number;
  frequency: FrequencyType;
  updatedAt: string;
  /** @nullable */
  doneAt: string | null;
  date: string;
  /** @nullable */
  description: string | null;
  name: string;
  id: number;
}
