/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type UpdateTaskComment403 = (typeof UpdateTaskComment403)[keyof typeof UpdateTaskComment403];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTaskComment403 = {
  NUMBER_403: 403,
} as const;
