/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateComment200User } from './updateComment200User';

export type UpdateComment200 = {
  content: string;
  updatedAt: string;
  createdAt: string;
  id: number;
  user: UpdateComment200User;
};
