/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTaskComment200User } from './updateTaskComment200User';

export type UpdateTaskComment200 = {
  content: string;
  updatedAt: string;
  createdAt: string;
  id: number;
  user: UpdateTaskComment200User;
};
