/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateArticleBodyImage } from './updateArticleBodyImage';
import type { ArticleContent } from './articleContent';
import type { ArticleTitle } from './articleTitle';

export interface UpdateArticleBody {
  /** @nullable */
  image?: UpdateArticleBodyImage;
  content?: ArticleContent;
  title?: ArticleTitle;
}
