/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type UpdateTaskComment404 = (typeof UpdateTaskComment404)[keyof typeof UpdateTaskComment404];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTaskComment404 = {
  NUMBER_404: 404,
} as const;
