/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { _36EnumsFrequencyType } from './_36EnumsFrequencyType';

export type UpdateTask200 = {
  displayIndex: number;
  writerId: number;
  userId: number;
  deletedAt: string;
  frequency: _36EnumsFrequencyType;
  description: string;
  name: string;
  recurringId: number;
  doneAt: string;
  date: string;
  updatedAt: string;
  id: number;
};
