/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UrlType } from './urlType';

/**
 * @nullable
 */
export type UpdateArticleBodyImage = UrlType | null;
