/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { AppSecret } from './appSecret';
import type { AppKey } from './appKey';
import type { _36EnumsOauthProvider } from './_36EnumsOauthProvider';

export interface UpsertOauthAppRequestBody {
  appSecret?: AppSecret;
  appKey: AppKey;
  provider: _36EnumsOauthProvider;
}
