/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { UserImage } from './userImage';
import type { Nickname } from './nickname';
import type { Id } from './id';

export interface User {
  teamId: string;
  /** @nullable */
  image: UserImage;
  updatedAt: string;
  createdAt: string;
  nickname: Nickname;
  id: Id;
}
