/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */
import type { DateString } from './dateString';
import type { WeeklyRecurringCreateBodyFrequencyType } from './weeklyRecurringCreateBodyFrequencyType';

export interface WeeklyRecurringCreateBody {
  name: string;
  /** @nullable */
  description?: string | null;
  startDate?: DateString;
  /** */
  frequencyType: WeeklyRecurringCreateBodyFrequencyType;
  weekDays: number[];
}
