/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * coworkers-api
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type WeeklyRecurringCreateBodyFrequencyType =
  (typeof WeeklyRecurringCreateBodyFrequencyType)[keyof typeof WeeklyRecurringCreateBodyFrequencyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyRecurringCreateBodyFrequencyType = {
  WEEKLY: 'WEEKLY',
} as const;
